#!/usr/bin/env ruby

require_relative '../lib/spellr'
require 'optparse'

list = false
interactive = false
config_file = nil

OptionParser.new do |opts|
  opts.on('--list', 'List files to be spellchecked') { list = true }
  opts.on('-i', '--interactive', "Runs the spell check interactively") { interactive = true }
  opts.on('-c', '--config FILENAME', String, "Path to the config file") { |file| config_file = file }
  opts.on_tail('-v', '--version', "Returns the current version") { puts Spellr::VERSION; exit }
  opts.on_tail('-h', '--help', "Shows this message" ) { puts opts; exit }
end.parse!

require_relative '../lib/config'
require config_file if config_file

# default config file is not required
begin
  require './.spellr_config' unless config_file
rescue LoadError
end

files = Spellr::FileList.new(*ARGV)

if list
  files.each { |f| puts f }
  exit
end


checker = Spellr::Check.new(files: files)
checker.check

exit checker.exit_code
