#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/spellr/cli'

::Encoding.default_external = ::Encoding::UTF_8
::Encoding.default_internal = ::Encoding::UTF_8

exit Spellr::CLI.new(ARGV).run
