name: CI

on: [push, pull_request]

jobs:
  rspec:
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, '3.0', 3.1, 3.2, 3.3, 3.4, ruby-head]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle exec rspec

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - run: COVERAGE=1 bundle exec rspec

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: 'coverage/*'
          retention-days: 1
        if: ${{ failure() }}

  rubocop:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - run: bundle exec rubocop

  spellr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - run: bundle exec spellr
  leftovers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - run: bundle exec leftovers

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4
        bundler-cache: true
    - run: bundle exec rake build

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: bin/docker_build

